twig:
    default_path: '%kernel.project_dir%/templates'
    form_theme: 'bootstrap_5_layout.html.twig'


when@dev:
    twig:
        cache: false
        auto_reload: true


when@test:
    twig:
        strict_variables: true
